s:/:\\\\:g
s:__EXE__:.exe:g
s:__OBJ__:.obj:g
s:__OBJS__:unixemu.obj unixdisk.obj:
s:__OBJLIST__:@$(ARGS):
s:__DEFRC__:'"'$(DOSRC)'"':
s:__RENAME__:@ren:
s:__AOUT2EXE__:@aout2exe:
s:__REMOVE__:@del:
s:__COPY__:copy:
s:__CC__:gcc:
s:__CPP__:cpp:
s:__CCOPTIONS__:-O:
s:__TERMLIBS__:-lpc:
s:__REGLIBS__::
s:__OTHERLIBS__::
s:__KCODEOPTION__:-s:
s:__MSBOPTION__::
s:__PREFIXOPTION__::
